import Head from 'next/head'
import Sidebar from '../components/Sidebar'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ibk Customer Support</title>
        <meta name="description" content="Generated by Demehin Ibukun" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  )
}
